packages:
  - 'app-shell'
  - 'overview'
  - 'stats'
  - 'details'

catalog:
  '@tailwindcss/vite': 4.0.12
  '@radix-ui/themes': 3.2.1
  tailwindcss: 4.0.12
  react: 19.0.0
  react-dom: 19.0.0
  '@originjs/vite-plugin-federation': 1.3.9
